name: Deploy to Azure App Service

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Azure Container Registry
        uses: docker/login-action@v1
        with:
          registry: lklocationexplorerregistry.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: lklocationexplorerregistry.azurecr.io/lk-location-explorer:latest, lklocationexplorerregistry.azurecr.io/lk-location-explorer:${{ github.sha }}
          cache-from: type=registry,ref=lklocationexplorerregistry.azurecr.io/lk-location-explorer:buildcache
          cache-to: type=registry,ref=lklocationexplorerregistry.azurecr.io/lk-location-explorer:buildcache,mode=max

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "lk-location-explorer"
          slot-name: "production"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          images: "lklocationexplorerregistry.azurecr.io/lk-location-explorer:${{ github.sha }}"
